version: "3.4"

services:
    api:
        build:
            context: .
        depends_on:
            - db
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - 5000:5000
        networks:
            - simple-network
        command: npm run dev
    db:
        image: postgres
        ports:
            - 2345:5432
        volumes:
            - postgres:/var/lib/postgresql/data
        env_file:
            - .env
        networks:
            - simple-network
networks:
    simple-network:
        driver: bridge

volumes:
    postgres:
