version: "3.4"

services:
  api:
    build:
      context: .
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
    command: npm start

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    user: root
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: "123456"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
